// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwmOfjvgAYLaYWokUgfhaSThcUHeNiUV4',
    appId: '1:100626877051:web:f44ee46218ce21535170de',
    messagingSenderId: '100626877051',
    projectId: 'myapp-91d2d',
    authDomain: 'myapp-91d2d.firebaseapp.com',
    storageBucket: 'myapp-91d2d.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMoAEUtesYcvNybsjlpkhcFeAZ-jmAFRU',
    appId: '1:100626877051:ios:bd94e902a337925c5170de',
    messagingSenderId: '100626877051',
    projectId: 'myapp-91d2d',
    storageBucket: 'myapp-91d2d.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwmOfjvgAYLaYWokUgfhaSThcUHeNiUV4',
    appId: '1:100626877051:web:a2eb266aecc22cb55170de',
    messagingSenderId: '100626877051',
    projectId: 'myapp-91d2d',
    authDomain: 'myapp-91d2d.firebaseapp.com',
    storageBucket: 'myapp-91d2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMoAEUtesYcvNybsjlpkhcFeAZ-jmAFRU',
    appId: '1:100626877051:ios:bd94e902a337925c5170de',
    messagingSenderId: '100626877051',
    projectId: 'myapp-91d2d',
    storageBucket: 'myapp-91d2d.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGU3MF5sNy_JuTEJDGe5sgAy_GxscWXwA',
    appId: '1:100626877051:android:90fd0a4af155a6e65170de',
    messagingSenderId: '100626877051',
    projectId: 'myapp-91d2d',
    storageBucket: 'myapp-91d2d.appspot.com',
  );

}